# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W5dXoJibSsQ-oS0f4dr1gvbVq-6OShua
"""

!pip install chatterbot
!pip install chatterbot_corpus

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer

bot = ChatBot('Pybot')
bot = ChatBot(
    'Pybot',
    storage_adapter = 'chatterbot.storage.SQLStorageAdapter',
    database_url = 'sqlite:///database.sqlite3' 
)

conversa = ListTrainer(bot)
conversa.train([
                'Oi?',
                'Olá',
                'Qual o seu nome?',
                'Pybot',
                'Prazer em te conhecer',
                'Igualmente',
                'Tudo bem?',
                'Muito bem e você?',
                'ótimo',
                'papo bom o nosso',
                'kkkkk',
                'adeus',
                'volte sempre'
])

trainer = ChatterBotCorpusTrainer(bot)
trainer.train('chatterbot.corpus.portuguese')

while True:
  resposta = bot.get_response(input("Usuário: "))
  if float(resposta.confidence) > 0.5:   # se a confiança da máquina na resposta for maior que 0.5
    print("Pybot: ", resposta)
  else:
    print('Desculpe, eu não entendi!')